name: "Rhaid Autofix"
description: "Scan and fix code issues in your repository using Rhaid."
branding:
  icon: "check-circle"
  color: "green"
inputs:
  path:
    description: "Path to scan/fix (default: .)"
    required: false
    default: "."
  mode:
    description: "Mode: scan or fix"
    required: true
    default: "scan"
  rules:
    description: "Rules (e.g., +format:*,+json:*)"
    required: false
  extra-args:
    description: "Extra arguments for Rhaid"
    required: false
    default: "--use-cache"
  args:
    description: "Additional CLI args for Rhaid"
    required: false
    default: "--json"
  install:
    description: "Install method: pipx_pypi | pipx_git | vendored"
    required: false
    default: "pipx_pypi"
  source_url:
    description: "Repo URL (pipx_git)"
    required: false
  source_ref:
    description: "Git ref/tag (pipx_git)"
    required: false
  python-version:
    description: "Python version"
    required: false
    default: "3.11"
runs:
  using: "docker"
  image: "Dockerfile" # You'll need to create a Dockerfile
